apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  template:
    spec:
      containers:
      - name: httpd
        image: kishorekumarkb/kishore1:latest
        ports:
        - containerPort: 80
